language: python

services:
  - docker

before_install:
  - docker build -t naamataulu-backend:latest .
  - docker run --entrypoint '/bin/sh' naamataulu-backend:latest -c 'cd src/naamataulu && python3 manage.py test api/tests'

script:
  - cd src/naamataulu && python3 manage.py test api/tests

