language: python

services:
  - docker

install: true

script:
  - docker pull wackymemes/naamataulu-backend:latest
  - docker build --cache-from wackymemes/naamataulu-backend:latest -t naamataulu-backend:latest .
  - docker run -e DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY -e DJANGO_DEBUG=$DJANGO_DEBUG -e DJANGO_SQLITE=$DJANGO_SQLITE -e DISABLE_COLLECTSTATIC=$DISABLE_COLLECTSTATIC -e WEB_CONCURRENCY=$WEB_CONCURRENCY --entrypoint '/bin/sh' naamataulu-backend:latest -c 'cd src/naamataulu && python3 manage.py test api/tests'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker tag naamataulu-backend:latest wackymemes/naamataulu-backend:latest ;
      docker push wackymemes/naamataulu-backend:latest ;
    fi