
version: '2'
services:
  web:
    restart: always
    build: .
    ports:
      - "8000:8000"
    env_file: .env-compose
    links:
      - postgres:postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres 
      PORT: 8000
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    env_file: .env-compose
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
