# Generated by Django 2.1.2 on 2018-12-18 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_auto_20181126_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('ISBN', models.CharField(max_length=13)),
                ('author', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=128)),
                ('published', models.DateTimeField()),
                ('cover', models.CharField(blank=True, max_length=128, null=True)),
                ('amazon_link', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraryAppProxy.BookInformation')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('library_type', models.CharField(choices=[('OL', 'OfficeLibrary'), ('EL', 'Elibrary'), ('UL', 'UnknownLibrary')], default='UnknownLibrary', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_loaned', models.DateTimeField()),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryAppProxy.Item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryAppProxy.Library'),
        ),
    ]
