# Generated by Django 2.1.2 on 2018-12-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryAppProxy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='information',
            new_name='info',
        ),
    ]
