# Generated by Django 2.1.2 on 2018-12-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryAppProxy', '0003_loan_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='info',
            new_name='item',
        ),
    ]
